apiVersion: v1
kind: Service

metadata:
  name: mongo-svc
  namespace: three-tier  

spec:
  selector:
    app: mongodb
  ports:
    - name: mongo-pvc
      protocol: TCP
      port: 27017
      targetPort: 27017

